package com.zafiru.problems;

public class Problem2 extends Problem {

    public Problem2() {
        super(2, "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
                "\n" +
                "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
                "\n" +
                "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
    }

    @Override
    public String answer() {

        int first = 1;
        int second = 2;
        int total = 0;

        while(second < 4000000)
        {
            if(second % 2 == 0)
            {
                total += second;
            }

            int tempSecond = second;
            second += first;
            first = tempSecond;
        }

        return String.valueOf(total);
    }
}
