package com.zafiru.problems;

import com.zafiru.utils.Helper;

import java.math.BigInteger;

public class Problem12 extends Problem {

    public Problem12() {
        super(12, "The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:\n" +
                "\n" +
                "1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...\n" +
                "\n" +
                "Let us list the factors of the first seven triangle numbers:\n" +
                "\n" +
                " 1: 1\n" +
                " 3: 1,3\n" +
                " 6: 1,2,3,6\n" +
                "10: 1,2,5,10\n" +
                "15: 1,3,5,15\n" +
                "21: 1,3,7,21\n" +
                "28: 1,2,4,7,14,28\n" +
                "We can see that 28 is the first triangle number to have over five divisors.\n" +
                "\n" +
                "What is the value of the first triangle number to have over five hundred divisors?");
    }

    @Override
    public String answer() {

        int expectedDividerCount = 500;
        int currentDividerCount = 0;

        long counter = 7;
        long value = 0;

        while (currentDividerCount <= expectedDividerCount) {

            counter++;

            value = 0;
            for (long i = 0; i < counter; i++) {
                value += i;
            }

            currentDividerCount = Helper.getDividers(value).size();
        }

        return String.valueOf(value);
    }
}
